### PR TITLE
Admin can store session in database

### LINKED ISSUE #73: Store sessions in database
Save information about the upcoming sessions and render those on the home page.
Information about sessions can be added/updated using the `Admin` interface.

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
**Status**:
- [x] Ready
- [ ] In Development
- [ ] On Hold

**Which issue does this PR fix?**: 
fixes #73 

This PR will allow admin to add and delete sessions. Also, Latest 3 sessions will be displayed on the homepage.

**Why do we need this PR?**:
Currently, We have to add sessions manually and to do that we have to edit page itself. Now, admin can add the session in one place and changes will be reflected to the homepage.

**Demo (optional)**:
Admin Screens:
image
image
image
image

User screen:
image

**Testing instructions:**:
1. `git checkout develop`
2. `python manage.py makemigrations`
3. `python manage.py migrate`
4. `python manage.py collectstatic`
5. `python manage.py runserver`
6.  To add sessions, goto `http://127.0.0.1:8000/admin/main/chatsession/add/`

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@jarifibrahim @nikhita @tapasweni-pathak Please review

**Comment by jarifibrahim** [comment]
@vaibhavsingh97 The Travis CI build failed because you didn't commit the `migration` files. Add the migration files and the build should be fixed.

**Comment by vaibhavsingh97** [comment]
@jarifibrahim I had made another PR #86. These are temp files which should not be in the main Repo.
We should run `makemigrations` to create new migration files based on the changes in model

**Comment by jarifibrahim** [comment]
@vaibhavsingh97 The migrations should be added to version control according to the [Django docs](https://docs.djangoproject.com/en/1.11/topics/migrations/#workflow). We won't need #86 if you add the migrations.

**Comment by tapaswenipathak** [comment]
@jarifibrahim I never knew that it is encouraged to push migrations file, I was thinking of adding it in .gitignore. I always thought that it is best to have what @vaibhavsingh97 added in the .travis.yml previously which used to be ```syncdb```. Thanks! 💮

**Comment by vaibhavsingh97** [comment]
@jarifibrahim Ok, I am adding migration and closing #86

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak @jarifibrahim Added requested changes. Please merge.

**Pull request merged**
