### PR TITLE
Issue and PR_Request template added

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
@tapasweni-pathak @jarifibrahim @nikhita @amarlearning 
Please review and merge

### CODE REVIEW

**Comment by nikhita** [comment]
@vaibhavsingh97 Github provides an automatic way to create an issue template and PR template. You don't need to create a docs folder separately for that. You can find the instructions here: https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/. :)

**Comment by vaibhavsingh97** [comment]
@nikhita I had followed the tutorial and according to the tutorial, we can put templates into `docs` folder.

**_Image for reference:_**
image
  
Should I remove and move the templates to root director?

**Comment by nikhita** [comment]
@vaibhavsingh97 @tapasweni-pathak You are right. But we still need the file to be named as `PULL_REQUEST_TEMPLATE.md` not `pull_request_template.md`. I think Github won't understand that it is a template unless named so.

I tried creating a PR to this repo - it did not show me the template. Can you check again to make sure this works?

**Comment by nikhita** [comment]
created #75 based on this. If you feel this PR works, feel free to go ahead and close that one.

**Comment by vaibhavsingh97** [comment]
@nikhita You are right, It will not work as they said file names are **not** case sensitive.
My bad I haven't read the doc carefully, I haven't read `not`

**Comment by tapaswenipathak** [comment]
@vaibhavsingh97 @nikhita Doesn't that mean that the file name is not case sensitive? Shouldn't this work? :P

**Comment by amarlearning** [comment]
@tapasweni-pathak `PULL_REQUEST_TEMPLATE.md` and `pull_request_template.md` both will work because file names are **not** case sensitive. :laughing:

**Pull request merged**
