### PR TITLE
modified settings.py

### PR DESCRIPTION
**Pull request by abarya**
Added Admins to the file settings.py

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
hey! @abhishekarya286 happy to see that you are curious to solve bugs but please don't create duplicate PR. #64 already solve the issue. There are many issues you can contribute. [Check here](https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/issues).  

Please keep these things in mind:
- Ask the maintainer/ person who created issue that you are interested in working on the issue
- Write the relevant message in PR like " fixed admin.py issue". You can read more about [here](https://github.com/erlang/otp/wiki/Writing-good-commit-messages)

**Comment by abarya** [comment]
okay, I'll keep it in mind next time.

**Comment by vaibhavsingh97** [comment]
@abhishekarya286 Please close this PR :smile:

**Comment by jarifibrahim** [comment]
Closing this PR. Duplicate of https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/pull/64

**Pull request closed without merging**
