### PR TITLE
 added coveralls.io badge to the readme.md file for issue #83 

### LINKED ISSUE #83: Add coveralls.io badge to README.md
Add coveralls.io badge to README.md file which can be found on https://coveralls.io/github/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io

### PR DESCRIPTION
**Pull request by coding-sunshine**
**Status**:
- [x] Ready
- [ ] In Development
- [ ] On Hold

**Which issue does this PR fix?**: fixes #83 

Brief description of what this PR does.
Just added coveralls.io badge to the readme.md file for issue #83 

**Why do we need this PR?**:

It solved issue #83 for adding coverall.io badge

**Demo (optional)**:

N/A

**Testing instructions:**:
N/A

**TODOs (if any)**:

**A picture of a cute animal (not mandatory but encouraged)**:

Sunshine

### CODE REVIEW

**Comment by nikhita** [comment]
@coding-sunshine Thank you for your first PR to OSHC! Everything looks perfect. :tada: 

Just a couple of minor comments:

- can you squash the commits to one commit?

- Since this PR solves #83, if you mention #83 as `fixes #83` in the PR description, Github will automatically close the issue when it's merged. That is, just add the issue number in front of the line `Which issue does this PR fix?: fixes #`. I'll edit the description now but just letting know for future reference. :)

And the image (and your github profile picture in effect) are just great! :heart:

**Comment by nikhita** [comment]
@coding-sunshine Oh no, I just saw that there is already a PR for this exact same thing in #88. :(

Since that PR was submitted before, I'll have to give chance to it first. I'm closing this PR for now. In case, #88 is not active, we'll re-open this.

Sorry for this, @coding-sunshine! Next time I think it will be a good exercise to check if someone is already working on it so you won't waste your time. :)

**Comment by coding-sunshine** [comment]
:) Thanks. Sorry for that, Just starting up with Open source. Will make sure from next time

**Comment by nikhita** [comment]
@coding-sunshine No problem, your PR was great though! :sparkles: :smile:

**Comment by cmdrwebdev** [comment]
Hi @vaibhavsingh97, I think @coding-sunshine  already fixed the issue.

**Comment by vaibhavsingh97** [comment]
Hi! @cmdrwebdev Don't give up so easily as you stated to solve issue so please solve issue and if you not able to solve issue we will guide you to help you. 😀

**Comment by cmdrwebdev** [comment]
Thanks @vaibhavsingh97, I'll request another PR in a bit.

**Pull request closed without merging**
