### PR TITLE
Hound CI test

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
This is testing PR for HoundCI. **Please don't merge.**

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@jarifibrahim HoundCI is not working. I have found GitHub repos where it's working but don't know why it's not working in our case :thinking:

**Comment by vaibhavsingh97** [comment]
I think we have to specify [config ](http://flake8.pycqa.org/en/latest/user/configuration.html)

**Comment by jarifibrahim** [comment]
@vaibhavsingh97 `flake8` works even without any config files (we just have to specify the file to check). I think Hound CI didn't report any errors because Travis CI failed. Can you fix the Travis CI build? Let's see what happens when Travis build is successful.

**Comment by vaibhavsingh97** [comment]
@jarifibrahim Ok, will push code in an hour or two :)

**Comment by vaibhavsingh97** [comment]
@jarifibrahim Now Travis CI build passed but still HoundCI passed the check without any violation

**Comment by jarifibrahim** [comment]
@vaibhavsingh97 Can you please add flake8 config file? I'm not sure why Hound CI isn't working. Let's see if it works with the config file.

**Comment by vaibhavsingh97** [comment]
@jarifibrahim I will add the config file and I recently had a conversation with the support team and they replied that they have asked the devs to look into this issue and will send us update in a day or two

**Comment by amarlearning** [comment]
Reopen whenever you need this

**Comment by amarlearning** [comment]
Try to keep the PR list clean. Feel free to reopen when you have new changes to push :)

**Pull request closed without merging**
