### PR TITLE
ValueError at /add_contest/ #148

### PR DESCRIPTION
**Pull request by sparkle-sparkle**
* make date input fields required
* define date pattern matching the pattern in the placeholder

**Checklist**

- [ ] My branch is up-to-date with the upstream `develop` branch.
- [ ] I have added necessary documentation (if appropriate).

**Which issue does this PR fix?**: fixes #

Brief description of what this PR does.
Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber"

**Why do we need this PR?**:

If relevant, please include a screenshot.

**Demo (optional)**:

Some tips for you to write the instructions:
- Prefer bulleted description
- Start after checking out this branch
- Include any setup required, such as migrating databases, etc.

**Testing instructions:**

If there is any work still left to do, please add it here.

**TODOs (if any)**:

**A picture of a cute animal (not mandatory but encouraged)**:

### CODE REVIEW

**Review by vaibhavsingh97 — APPROVED** [review]
Thanks for contributing 😄 This PR is ready to ship 🚀 
image
image

**Comment by sparkle-sparkle** [comment]
Happy to help 😄

**Review by tapaswenipathak — APPROVED** [review]
Thanks for the work!

**Comment by sparkle-sparkle** [comment]
You're welcome

**Pull request merged**
