### PR TITLE
footer template added

### LINKED ISSUE #34: Adding template for footer
According to DRY Principle, The aim should be reducing the repetition of information.
The footer is present in the index.html file and in future we will have more pages, so to avoid repetition we will add this in the template.

Existing behavior: Footer code snippet is present in the index.html
Actual Behaviour: Footer should be present as a template so that we can just use the code-block

**I am interested in working on this issue**

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
fixes #34 #38

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak @nikhita  @jarifibrahim Please review

**Comment by nikhita** [comment]
@vaibhavsingh97 LGTM from my side!

Just updated the PR description to say `fixes #34`. Did you intend on any more PRs for fixing #34? If yes, feel free to remove that. :smile:

**Review by jarifibrahim — APPROVED** [review]
Looks good.

**Comment by nikhita** [comment]
Merging it since it got 2 approvals! :star2:

**Pull request merged**
