### PR TITLE
[WIP] Added test case for Chat sessstion View, Contest Form

### LINKED ISSUE #179: Add test cases
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in our slack channel at https://opensourcehelp.slack.com/. Request invite [here](https://opensourcehelp.herokuapp.com)

**Description**:
- Add test case for authentication using Email
- Add test case for contest form and Chat session form

**Would you like to work on this issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
**Checklist**

- [x] My branch is up-to-date with the upstream `develop` branch.
- [ ] I have added necessary documentation (if appropriate).

**Which issue does this PR fix?**: fixes #179

### CODE REVIEW

**Review by tapaswenipathak — APPROVED** [review]
Great! 

- [ ] README update to run test

I cleaned up few things on this. When I say ```python3 oshc/manage.py test```, it doesn't run the test. If I say ```python3 manage.py test``` after ```cd``` into oshc, it works! also if I say ```python3 oshc/manage.py test <app_name>``` it works. 🤔  Did you try this out, do you have a good read for this? 

cc @jarifibrahim.

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak This PR still has issues so please leave it for a moment

**Comment by tapaswenipathak** [comment]
What issues? 🤔 I am in the process of fixing this coverage part and not specifying all apps.

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak issue with `ChatSessionCreateTestCase`

**Comment by tapasweni-pathak** [comment]
Oh yep, this one I remove, if I fix the issue with coverage before.

**Pull request merged**
